import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";

import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";

import CustomHeader from "@/components/Global/CustomHeader";
import CustomFooter from "@/components/Global/CustomFooter";
import DelayedPopup from "@/components/Global/DelayedPopup";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Switzerland Consulting",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body
        className={`${inter.className} min-h-screen flex-row justify-between`}
      >
        <NextIntlClientProvider messages={messages}>
          <div className="sticky top-0 z-[999] w-full items-center border-b border-gray-300 bg-gradient-to-b from-zinc-200 font-mono text-sm backdrop-blur-2xl">
            <div className="flex w-full justify-center  pb-6 pt-8  dark:border-neutral-800 dark:bg-zinc-800/30 dark:from-inherit ">
              <CustomHeader />
            </div>
          </div>
          <div className="flex-1">{children}</div>
          <div>
            <CustomFooter />
          </div>
          <div>
            <DelayedPopup />
          </div>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
